name: Install Dependencies

on:
  push:
    branches:
      - main  # Replace with the branch name of your choice

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Replace with the Node.js version you prefer

      - name: Install dependencies
        run: npm install
